Hi guys,

I tried to run tests for flink-python with ./dev/lint-python.sh by following README. But it reported it couldn't find flake8, error as



./dev/lint-python.sh: line 490: /.../flink/flink-python/dev/.conda/bin/flake8: No such file or directory



I've tried ./dev/lint-python.sh -f, also didn't work.

I suspect the reason may be that I already have an anaconda3 installed and it conflicts with the miniconda installed by flink-python somehow. I'm not fully sure about that.

If that's the reason, I think we need to try to resolve the conflict because anaconda is a pretty common package that developers install and use. We shouldn't require devs to uninstall their existing conda environment in order to develop flink-python and run its tests. It's better if flink-python can have a well isolated environment on machines.