Using following test in our framework,

./run-pybot.py -s rest2ldap_group.readembedded -t monitor_endpoint -v dj

 is possible to reproduce an issue with getting an info from  /admin/monitor .

After installation of server with HTTP Connection handler enabled, the test tries to access mentioned endpoint with following GET request:

http://pyforge.example.com:8080/admin/monitor?_prettyPrint=true

The response returns status code 500 Internal Server Error:

{ 
   "code" : 500, 
   "reason" : "Internal Server Error", 
   "message" : "The provided value \"20180223022424\" is not a valid 
                generalized time value because it contains an invalid
                character '2' at position 12" 
}

 