Discovered with stress tests targeted to groups.

The test use 2x DSRS topology.

	We install 2 DSRS instances
	Configure replication
	Add 2000 groups
	Stop both instances
	Start both instances
	Run searchrate



The test finishes, but we have an error message in logs:


(ERROR) [25/Jun/2018:19:17:13 +0200] category=SYNC severity=ERROR msgID=-1 msg=For input string: "P��"

The timestamp from the message relates to step 5. above. I can see an error message in start-ds output:


[25/Jun/2018:19:17:13 +0200] category=SYNC severity=ERROR msgID=179 msg=Replication server 8 was attempting to connect to replication server comte.internal.forgerock.com/172.16.204.14:8990 but has disconnected in handshake phase. Error: SocketTimeoutException(Read timed out)

I have attached full start-ds output, because there are also some WARNING messages.

To reproduce the issue use following command and attached config file (adjust host_name and java_home):


./run-pybot.py -v -c perf -s perf_comparison.GroupComparison -t SearchRate_1.1 OpenDJ
