found with rev OpenDJ 7.0.0-SNAPSHOT (1d33bc905c3)

We have a test to verify the issue OPENDJ-4598
 It sets up 3 servers then loops on configuring replication between them, running a modrate, then unconfiguring replication.
 This test has started failing randomly with:

/home/jenkins/workspace/OpenDJ-build_master-CPMER56E632EMKNXZEURRUYWFHY72MGZDGZHN7BYLM5SGO6GS6PA/results/20191224-163406/replication_group3/HighCPUSpin/DJ1/opendj/bin/dsreplication initialize-all -h openam.example.com -p 4446 -b dc=example,dc=com -I admin -w password  -X -n	
20:27:53.865	WARN	ERROR:
-- rc --
returned 12, expected to be in [0]
-- stdout --

Initializing base DN dc=example,dc=com with the contents from
openam.example.com:4446:
0 entries processed (0 % complete).

-- stderr --

Error during the initialization with contents from server
openam.example.com:4446. Last log details: [24/Dec/2019:19:25:52 +0000]
severity="NOTICE" msgCount=0 msgID=org.opends.messages.backend-413
message="Initialize Backend task dsreplication-initialize-7 started
execution". Task state: STOPPED_BY_ERROR. Check the error logs of
openam.example.com:4446 for more information.
See /tmp/opendj-replication-9020454471481907338.log for a detailed log of this
operation.
Details: com.forgerock.opendj.cli.ClientException: Error during the
initialization with contents from server openam.example.com:4446. Last log
details: [24/Dec/2019:19:25:52 +0000] severity="NOTICE" msgCount=0
msgID=org.opends.messages.backend-413 message="Initialize Backend task
dsreplication-initialize-7 started execution". Task state: STOPPED_BY_ERROR.
Check the error logs of openam.example.com:4446 for more information.


and in logs:

--- Check for error patterns in "/home/jenkins/workspace/OpenDJ-build_master-CPMER56E632EMKNXZEURRUYWFHY72MGZDGZHN7BYLM5SGO6GS6PA/results/20191224-163406/replication_group3/HighCPUSpin/DJ2/opendj/logs/errors" file ---	
20:28:29.259	WARN	(ERROR) [24/Dec/2019:19:25:55 +0000] category=SYNC severity=ERROR msgID=335 msg=Domain dc=example,dc=com: the server with serverId=dj1 is unreachable in Replication Server=RS(dj2, 8992), an initialization message of type ErrorMsg cannot be sent to its destination server. Details: routing table is empty	
20:28:29.261	WARN	(ERROR) [24/Dec/2019:19:27:53 +0000] category=SYNC severity=ERROR msgID=79 msg=The following error has been received : Other: The following servers did not acknowledge initialization in the expected time for domain dc=example,dc=com. They are potentially down or too slow. Servers list: [dj3, dj2]


To try and reproduce this issue:

./run-pybot.py -nvs replication_group3 -t high_cpu_spin opendj

