Many test failures appear to result from bind failures due to port conflicts.  This can arise in normal use as well.  Presently the code swallows the exception (with an error log) at a low level.  It would probably be useful to throw the exception far enough up the stack to trigger retry with a new port (in tests) or a high-level (perhaps even fatal) error message (in normal use).