Client unwraps the ExecutionException before throwing it to the user code.
The member never does it. It also does not happen on other async proxies. Client should not unwrap.

RingbufferQuorumReadTest & ClientRingbufferQuorumReadTest are a good example how to reproduce it.

After fixing, clean-up this test by removing the catch clause and adding
`expectedException.expectCause(isA(QuorumException.class));`

https://github.com/tombujok/hazelcast/blob/9bb5df6812c50ac769bd93fdf72a5a3a5b7db34b/hazelcast/src/test/java/com/hazelcast/quorum/ringbuffer/RingbufferQuorumReadTest.java#L148-L152
  