I get the following exception, but looks like it does not affect the correct behavior.
Should not be logged to SEVERE?

```
SEVERE: [127.0.0.1]:5703 [group] [3.2-SNAPSHOT] null
java.lang.NullPointerException
    at com.hazelcast.spi.impl.BasicOperationService$RemoteCallKey.hashCode(BasicOperationService.java:974)
    at java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:896)
    at com.hazelcast.util.scheduler.SecondsBasedEntryTaskScheduler.scheduleIfNew(SecondsBasedEntryTaskScheduler.java:213)
    at com.hazelcast.util.scheduler.SecondsBasedEntryTaskScheduler.schedule(SecondsBasedEntryTaskScheduler.java:61)
    at com.hazelcast.spi.impl.BasicOperationService.scheduleBackup(BasicOperationService.java:513)
    at com.hazelcast.spi.impl.BasicOperationService.sendBackups(BasicOperationService.java:501)
    at com.hazelcast.spi.impl.BasicOperationService.doRunOperation(BasicOperationService.java:363)
    at com.hazelcast.spi.impl.BasicOperationService.access$1000(BasicOperationService.java:75)
    at com.hazelcast.spi.impl.BasicOperationService$LocalOperationProcessor.run(BasicOperationService.java:815)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at com.hazelcast.spi.impl.BasicOperationService$OperationThread.run(BasicOperationService.java:943)
```
