grunt> cd s3://agile_data
2012-02-16 22:05:59,461 [main] ERROR org.apache.pig.tools.grunt.Grunt - ERROR 2999: Unexpected internal error. Invalid hostname in URI s3://agile_data
Details at logfile: /home/hadoop/pig_1329429351155.log

I think the next behavior is already documented/bug filed:

grunt> cd 's3://agile_data'
2012-02-16 22:02:28,489 [main] ERROR org.apache.pig.tools.grunt.Grunt - ERROR 2999: Unexpected internal error. java.net.URISyntaxException: Illegal character in scheme name at index 0: 's3://agile_data'
Details at logfile: /home/hadoop/pig_1329429351155.log